#+TITLE:Generating a new SSH key and adding it to the ssh-agent

After you've checked for existing SSH keys, you can generate a new SSH key
to use for authentication, then add it to the ssh-agent.

* Generating a new SSH key
1. Open Terminal.
2. Paste the text below, substituting in your GitHub email address.
#+BEGIN_EXAMPLE
ssh-keygen -t rsa -b 4096 -C "your_email@example.com"
# Creates a new ssh key, using the provided email as a label
Generating public/private rsa key pair.
#+END_EXAMPLE

3. When you're prompted to "Enter a file in which to save the key," press Enter.
This accepts the default file location.
#+BEGIN_EXAMPLE
Enter a file in which to save the key (/Users/you/.ssh/id_rsa): [Press enter]
#+END_EXAMPLE

4.At the prompt, type a secure passphrase. For more information,
see "[[https://help.github.com/articles/working-with-ssh-key-passphrases][Working with SSH key passphrases]]" .
#+BEGIN_EXAMPLE
Enter passphrase (empty for no passphrase): [Type a passphrase]
Enter same passphrase again: [Type passphrase again]
#+END_EXAMPLE

* Adding your SSH key to the ssh-agent

Before adding a new SSH key to the ssh-agent, you should have
[[https://help.github.com/articles/checking-for-existing-ssh-keys][checked for existing SSH keys]] and [[https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent#generating-a-new-ssh-key][generated a new SSH key]].

1. Ensure ssh-agent is enabled:
#+BEGIN_EXAMPLE
# start the ssh-agent in the background
eval "$(ssh-agent -s)"
Agent pid 59566
#+END_EXAMPLE

2. Add your SSH key to the ssh-agent. If you used an existing SSH key rather than
[[https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent#generating-a-new-ssh-key][generating a new SSH key]], you'll need to replace id_rsa in the command with
the name of your existing private key file.
#+BEGIN_EXAMPLE
$ ssh-add ~/.ssh/id_rsa
#+END_EXAMPLE

3. [[https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account][Add the SSH key to your GitHub account]].
