#+TITLE:Testing your SSH connection

After you've set up your SSH key and added it to your GitHub account, you can
test your connection.

Before testing your SSH connection, you should have:

- [[https://help.github.com/articles/checking-for-existing-ssh-keys][Checked for existing SSH keys]]
- [[https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent][Generated a new SSH key]]
- [[https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account][Added a new SSH key to your GitHub account]]

When you test your connection, you'll need to authenticate this action using
your password, which is the SSH key passphrase you created earlier. For more
information on working with SSH key passphrases,
see "[[https://help.github.com/articles/working-with-ssh-key-passphrases][Working with SSH key passphrases]]".

1. Open Terminal.

2. Enter the following:
#+BEGIN_SRC bash
ssh -T git@github.com
# Attempts to ssh to GitHub
#+END_SRC

You may see one of these warnings:
#+BEGIN_EXAMPLE
The authenticity of host 'github.com (192.30.252.1)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)?
#+END_EXAMPLE

#+BEGIN_EXAMPLE
The authenticity of host 'github.com (192.30.252.1)' can't be established.
RSA key fingerprint is nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)?
#+END_EXAMPLE

=Note=: The example above lists the GitHub IP address as 192.30.252.1.
When pinging GitHub, you may see a range of IP addresses. For more information,
see "[[https://help.github.com/articles/what-ip-addresses-does-github-use-that-i-should-whitelist][What IP addresses does GitHub use that I should whitelist?]]"

3. Verify that the fingerprint in the message you see matches the following
message, then type =yes=:
#+BEGIN_EXAMPLE
Hi username! You've successfully authenticated, but GitHub does not provide shell access.
#+END_EXAMPLE

You may see this error message:
#+BEGIN_EXAMPLE
...
Agent admitted failure to sign using the key.
debug1: No more authentication methods to try.
Permission denied (publickey).
#+END_EXAMPLE

This is a known problem with certain Linux distributions. For more information,
see "[[https://help.github.com/articles/error-agent-admitted-failure-to-sign][Error: Agent admitted failure to sign]]".

4. Verify that the resulting message contains your username. If you see a message
that contains "access denied," see "[[https://help.github.com/articles/error-permission-denied-publickey][Error: Permission denied (publickey)]]".

If you receive a message about "access denied," you can
[[https://help.github.com/articles/error-permission-denied-publickey][read these instructions for diagnosing the issue]].

5. If you're switching from HTTPS to SSH, you'll
[[https://help.github.com/articles/changing-a-remote-s-url][need to update your remote repository URLs]].
