#+TITLE: 聊聊技术人如何与甲方客户打交道

@See https://mp.weixin.qq.com/s/zqGo90RRsgX6NP03zr772w

客户是谁？
所有你需要提供服务的人都是客户，产品经理，老板，甲方客户，相关干系人等等，不同客户有不同的应对策略。今天主要与
聊聊甲方客户的沟通交流，下面我就简单从三个角度聊聊，不管是自己创业、拉私活、帮公司对接项目，都用的上。

* 需求
一、统一接口人，避免客户直接接触团队内部人员，统一有一个人对接需求，便于需求管理，也防止打乱内部部署计划。
二、不少客户不懂技术，不要用技术化的语言交流，要更多去类比，形象化描述。把技术的外在使用变现，传达给他们，具体
的技术细节完全没必要，沟通起来无异于对牛弹琴。
三、需求沟通完，要当面复述，确保需求的准确性。时刻保持沟通，不可意会需求，导致后期被无限放大，错过了工期，后期
很不好交付。最好的办法是出业务原型，面对面确认。
四、心里有个预期：一成不变的需求不存在，哪怕客户说板上钉钉的需求，当见到真实的东西，实际操作后，一样会一堆东西
提出来。没用之前，一切都是抽象的，操作后，体验好不好，立竿见影。
五、有些需求实施起来确实有难度，但不能说做不了，当前情况下，凡是符合逻辑的需求，基本都可以实现，关键点在 ROI，
就是投入产出比，也成为投资回报率。你说做不了，他会怀疑你的专业性，把利害得失摆在桌面上让客户选。
六、也有些一看明显是不合理的需求，但客户非要不可。生意就是生意，不能由着自己性子来。甲方是出资方，服务提供方尽
量提供，能以最小成本实现最好。
七、要引导要挖掘，有时候客户不知道自己要什么，没办法描述清楚，你要站在他的角度，以同理心态，帮助他梳理，增加信
任感，要让客户觉得，你是来帮助他解决问题的，而不是来挣他的钱，争取发展成为长期合作伙伴。当然要把握一个度，合同
确定的情况下，过度的发散，会导致衍生出来很多工作量。

* 甲方接口人
一、及时汇报进度，每一个人对不可见的事态发展都会不踏实，客户也不例外，一般都会设置甲方项目经理的岗位，对这个人
要时不时的汇报实施进度。怕的不是有问题，怕要到交付节点了，还有很多东西没落地。
二、与甲方接口人要搞好关系，这是一个窗口，作为实施方一般没办法直接接触到甲方决策人，但可以通过他间接接触。另外，
人员流动总是存在的，他去其他地方时，如果有合作的机会，他会考虑到你。
三、终究是博弈关系，各自服务于各自的机构，沟通协作上以不损害各自的利益为前提。
四、把活做漂亮，就是帮助他在公司里做好业绩。他对上面好交代，工作开展会顺利些，有些利益会帮你争取，比如后续的项
目，项目款结算等等。

* 实施过程
一、实施过程中，免不了与甲方高层打交道，有时候对话要平等。小决策自己拍板，决策完，事后回报。大事项还是回去请示，
高层与高层平等对话，让高层去权衡利弊，自己只做分内事即可。
二、前方实施时，实施项目经理是与公司的纽带，要及时汇报请示，透明工作，自家的领导对工作进展熟知时，在与甲方的领导
沟通时，心里也有底。
三、各种文档要齐全，虽然有时候客户根本不会看，但需要的时候要有。把工作量摆清楚，让客户觉得价有所值。
四、不可太斤斤计较，实施过程中难免会有小修小改，顺手的事就做了。当然不能像有些销售一样，随便应承。需要把东西摆
清楚，虽然花几分钟个把小时能做的事，但事儿要做的专业，就要按照流程走。大的变动，要走需求变更，在合理的范围内，
合同工作量是能覆盖的。
五、积极响应客户需求，写代码的小伙伴都知道，不管是同步处理还是异步处理，第一时间做出响应，程序才能做出下一步判
断。实时响应后，让客户觉得你是在重视他们，这一点很重要。
六、实施过程中，深入客户业务，挖掘其他机会。业务都是相关的，系统建设可以迭代完善，但系统完整也是必要的。

