#+TITLE: 远程工作如何提高效率

@See https://geekplux.com/2020/02/18/how-to-be-efficient-on-remote-work

别看我一直上学和上班，但实际上中间穿插着不少段远程工作的经历。远程工作其实在程序员群体中，或者说在创作型工作者
群体中已经流行很多年了。而这次疫情来得太突然，导致很多没有远程经验的人第一次远程办公，所以这里分享一些我个人的
经验，希望能提供些许帮助。

我认为远程工作提效可以分成两个方面，一个是 =与人合作= ，一个是 =自身效率= 。

* 与人合作
远程工作不是单打独斗，仍是需要和人打交道的，而且沟通频率可能比在公司还高。以下四点是我在多次远程工作中得出的
经验教训：

** 1 熟悉工具
如何连接远程电脑、如何登录 VPN、如何使用各类软件等等都要了解清楚并做到熟练。把工作流程全部 =打通= ，减少
自己的重复劳动，也节省每次沟通前的准备时间，还保证了即使 IT 同事不在的情况下也不至于被工具卡住项目进度。
远程工作时大家在线时间不是固定的，所以指望临时求助同事是对彼此都不高效的方式。

** 2 主动沟通
把做完的、正在做的、接下来要做的都要及时更新给其他人。事事有响应，件件有着落，不仅要口头通知，最好是形成
一个自己的 =工作文档= ，把实时的进度更新上去，让其他人一目了然，也是给自己一个计划和交代。远程工作不比在公
司，虽然在公司也是各干各的事，但是只要想沟通是可以直接够得着的，而远程沟通成本太高，所以应该 =尽量减少沟通
次数，提高单次沟通的效率= 。

** 3 主动坦白
没做完就是没做完，不要硬撑着说做完了，然后暗下决心晚上加班搞定。这很容易陷入恶性循环：要面子死扛 -> 带着
心理负担加班 -> 状态不好又没做完 -> 要面子死扛。技术债务有时比赌债还可怕，一不小心就还不起了。而且这种
“假性完成”还会严重影响同事和团队的进度，别人以为做完了，接下来的计划都建立在你做完的基础上，而实际没做
完，等之后再推倒重来就难了，说不定给各位同事都造成影响。

所以大方地承认自己没做完更好，即使是因为偷懒划水没做完，也要直接坦白。其实远程工作大家的效率不一定都是满转的，所以遇到卡壳、做不完都太正常了，直接承认，说不定对方也说“我也摸鱼了一天”然后其乐融融。

** 4 配合为主
面对面都有可能争吵，远程工作中就更避免不了摩擦了，所以要让步、妥协、共赢。也不是说要收敛个性，但能理解的
要尽量理解，因为很多摩擦是因为沟通不到位所致。用文字表达出语气是很难的事，用语音去感知表情也是很难的事，
透过这些去知道对方的工作状态更加是不可能的事。你也肯定有被环境打断或状态不好的时候，所以多换位思考，可能
就没什么。

* 自身效率
接下来说说如何提高自身效率，这方面每个人都大有心得，我这里就简单说说自己的经验，班门弄斧了。

** 1 要有仪式感
远程工作的时候，即使在家我也会起床换身衣服，或设立个仪式，让大脑知道自己是在工作，而不是休闲。仪式感有利于
自己进入工作状态。

** 2 营造好的办公环境
每个人喜欢的办公环境不一样，这里要挑选你喜欢的，而不是随便一个地方都可以。比如我就喜欢声音嘈杂的地方，肯德
基星巴克等等，我还喜欢躺床上写代码写文章。合适的地方舒服的姿势会让人事半功倍。

** 3 切割时间
设立自己的上下班时间，把生活工作切割开。这点很重要，不明确地切割开，很容易导致时间在拖延中浪费。对于一段
模棱两可的时间，我们更倾向于不那么辛苦地度过。只有明确的告诉自己和家人，“这段时间是我的工作时间，请不要
打扰我”，才能保证自己是真正的在工作。而且要选择自己效率最高的时间段作为工作时间，说不定 2 个小时干 8
个小时的活，提前下班呢。

** 4 关闭社交软件
这点我相信大家都懂，手机扔一边，工作乐无边。

* 尾
其实我之前录了一个 vlog 来讲这个话题，但在镜头面前还是太羞耻了，紧张的不像我自己，所以还是写下来算了。只是
一点微小的经验，希望有用。最后再提供一些远程工作相关的书籍和链接，有兴趣的同学自行浏览吧：

- 当年的神书：[[https://geekplux.com/r/remote2][《重来 2》]]
- 中国远程工作资料大全：https://github.com/greatghoul/remote-working
- 国内最好的远程工作社区：[[https://eleduck.com/][电鸭社区 - 互联网工作者们的聚集地]]
- [[https://geekplux.com/2019/07/31/how-to-get-jobs-pay-80-dollars-per-hour-1/][如何找到时薪 80 美元的远程工作]]
