#+TITLE: 关于自我成长的一些不成熟的小建议


下面是我的一些不成熟的小建议，希望对大家有帮助。

1. 多从身边的人身上吸收经验

“人类的本质是复读机”。

这个道理是真的，人类学习的过程其实就是模仿的过程，从模仿的过程中吸收经验，再根据经验进行创新。所以现在这个阶段主要是要多从身边的人身上吸收经验。如果你有一个你认同的且很棒的导师，那恭喜你，学习他对问题的思考方式，学习他的学习方式。


如果你觉得你的导师是个傻逼，他在技术上，思想上，方法论上都无法帮助到你，这种情况其实还挺多的，毕竟不是每个人都善于帮助一个菜鸟的。

如果你不幸遇到这样一个导师，定一个小目标，不要成为他那样的人，如果你觉得公司里充满了这样的人，保持学习，然后走人。

2. 低调做人高调做事

做人要低调，不是事事想着出风头，这个九年义务教育应该都已经教会大家怎么做了，我就不赘述了。

高调做事我的意思是，让别人知道你在做什么，不是埋头苦干，做出了产品要让大家知道，要去推广它，特别是做大数据行业的，很多的项目都是对内的，你不说别人不知道你能解决他的痛点，你不说别人永远不知道你有多牛逼。

3. 深耕技术

我们是技术人，我们是靠技术吃饭的，技术的深度和广度决定了我们在未来可以担任多高的职位，工资能达到多高的水平，可以工作到多大的年纪....（这个怎么说起来好像有点心酸）。

总之技术是我们吃饭的家伙，是重中之重，至于如何深耕技术，应该不是这一篇需要讨论的内容，有空我会另起一篇文章。


4. 提升沟通表达能力

上面说到要让别人知道你在做什么，如果你不知道如何让别人知道的话，那就多做点分享！分享的过程就是一个提高表达能力的过程。

会做和会说不是同一码事，说得庸俗一点升职加薪在很多公司里的评判标准不仅仅是你会做，你还得会说。把你做的说得清楚，说得牛逼。吹牛逼是一项很重要的职场技能，不要以为你是程序猿就可以把这个技能抛弃。

另外，写公众号的这段日子，也让我知道了对于一个技术点自己懂和能说出来和能写出来真的是三件不同的事情，我太难了。




5. 要有规划

你的职业规划是什么？


这个问题面试官有99%的概率会问，除去用来应付面试官的那些说辞，你真的有好好规划过你的职业生涯吗。

这里建议大家找一个夜黑风高的夜晚，卸下世俗的欲望，抹去焦虑的心情，放空自己...... 然后......

想想自己对自己的期望是怎么样的，三年后自己要达到什么水平，五年后呢，要很具体的，不要想虚的，什么做架构师啊，技术总监啊，那你问问你自己你知道要到什么程度才能成为架构师或技术总监吗？

有了目标之后还得制定好自己如何一个阶段一个阶段地达到自己的期望的一个行动方案。不要像无头苍蝇一样，做无目标的努力。

