#+TITLE: 科学上网软件信息收集

* Lantern
俺那个【自动同步翻墙工具】的 BT sync 密钥：BTLZ4A4UD3PEWKPLLWEOKH3W7OQJKFPLG

“Lantern”是一款新兴的翻墙工具。“蓝灯”是它的中文名。
它的特色是：开源并且跨平台（Windows、Linux、Mac OS）。

官方网站是 https://getlantern.org/
（必须翻墙才能访问）

除了官网，还可以利用它在 GitHub 上的官方帐号，【免翻墙】下载安装包。具体请访问如下页面：
https://github.com/getlantern/lantern-binaries

更详细的介绍，请参见俺的博文《“如何翻墙”系列：Lantern（蓝灯）——开源且跨平台的翻墙代理》
https://program-think.blogspot.com/2015/08/gfw-lantern.html

* I2P
俺那个【自动同步翻墙工具】的 BT sync 密钥：BTLZ4A4UD3PEWKPLLWEOKH3W7OQJKFPLG

“I2P”是老牌的翻墙工具，并且是“开源项目”。
它非常类似于 TOR（TOR 叫“洋葱路由”，而 I2P 是“大蒜路由”）。它俩的主要用途是“隐匿身份”，翻墙只是顺带的附加用途。

I2P 的安全性和坚挺程度比 TOR 更强，换来的代价是速度很慢。
所以 I2P 主要是用来作为备用翻墙工具。当你常用的工具失效时，就可以拿它来救急。

官方网站是 https://geti2p.net
（必须翻墙才能访问）

要运行该软件，系统中需要事先安装 Java 环境。
Java【不是】I2P 的组成部分，需要另外单独安装。
你可以去它的官网下载 Java 的安装包，网址如下：
https://java.com/download

更详细的介绍，请参见俺的博文《“如何翻墙”系列：简单扫盲 I2P 的使用》
https://program-think.blogspot.com/2012/06/gfw-i2p.html

* Tor
俺那个【自动同步翻墙工具】的 BT sync 密钥：BTLZ4A4UD3PEWKPLLWEOKH3W7OQJKFPLG

“TOR”是老牌的翻墙工具，并且是“开源项目”。
它的主要用途是“隐匿身份”，翻墙只是顺带的附加用途。

官方网站是 https://www.torproject.org/
（必须翻墙才能访问）

本目录提供的安装包，还附带了安装包的签名文件（扩展名为 asc）。
为了保险起见，需要验证一下签名。
验证签名的方法，参见 TOR 官网的如下文档
https://www.torproject.org/docs/verifying-signatures.html.en

更详细的介绍，请参见俺的如下几篇博文：
《“如何翻墙”系列：TOR 已复活——meek 流量混淆插件的安装、优化、原理》
https://program-think.blogspot.com/2014/10/gfw-tor-meek.html
《“如何翻墙”系列：关于 TOR 的常见问题解答》
https://program-think.blogspot.com/2013/11/tor-faq.html
《“如何翻墙”系列：戴“套”翻墻的方法》
https://program-think.blogspot.com/2009/09/break-through-gfw-with-tor.html

* BTsync
俺那个【自动同步翻墙工具】的 BT sync 密钥：BTLZ4A4UD3PEWKPLLWEOKH3W7OQJKFPLG
