#+TITLE: 购买 VPS 服务器有哪些需要注意的事项？

@See https://p3terx.com/archives/what-should-i-pay-attention-to-when-purchasing-a-vps-server.html

* 服务条款(TOS)
要购买 VPS 之前，先看好 *服务条款 (TOS)* 或 *用户可接受政策 (AUP)* ，看清楚 VPS 禁止什么、不允许做什么，免得被封。

一般来说主要是指的：网络滥用、硬件滥用、下载盗版资源、下载 BT 行为 (P2P)、存放色情内容等。

* 更换 IP 政策
如果你要购买 *日本、美国等热门地区的 VPS* ，这些热门地区 *同代理软件及配置被墙几率要高于其他地区* ，如果不支持更换 IP，被墙后你就只能重新购买 VPS 。

IDC 会把 *更换 IP 政策* 写在 *服务条款 (TOS)* 中，但是关于 *被墙 IP 更换政策* IDC 往往不会写上。所以要么 *注册后联系客服询问* 。如果有 *官方交流群、公告频道* 的话，也可以看看有没有写。

* 退款政策
*IDC 的 服务条款 (TOS) 是必须注明退款政策的* ，如果你翻遍了 *服务条款 (TOS)* 也没找到写退款的地方，那么说明是 *不接受退款* 。当然即使是不接受退款，也应该注明的，如果不注明，那么 *不推荐你购买这家 IDC* 。

*如果 IDC 不支持退款* ，那么你购买 VPS 前要谨慎一些，因为就算你不满意也无法退款。

*如果 IDC 支持退款* ，但是没多少家 IDC 接受无理由退款，往往会做一定的限制，例如：

 - *超过一定时间内没有联系客服退款* ，则不接受退款。
 - *流量使用超过多少 GB* ，不接受退款。
 - *IP 被墙后* ，不接受退款。
 - *违反用户使用条例后* ，不接受退款（例如违规 VPS 被封，想要退款）。

* VPS 虚拟化
目前中小型 IDC 的 VPS 虚拟化无非就是： *OpenVZ、KVM、XEN、VM-Ware* 。

你要说 OpenVZ 是超售专用虚拟化，也太绝对，因为其他两个的虚拟化也能实现超售，不过 OpenVZ 的更容易超售，所以价格普遍更便宜。

而 *OpenVZ 无法安装 TCP 加速软件*（至于 VPS 内安装虚拟机来实现安装使用 BBR 行为，首先安装虚拟机是违规行为，其次该方式会造成性能损失，且对新手不友好）。

*KVM、XEN、VM-Ware 都可以安装 锐速、LotServer 以及 更换内核开启 BBR* 。

所以除非你实在预算少，否则我更 *推荐你选择 KVM、XEN、VM-Ware 虚拟化* 的 VPS 。

另外，XEN 虚拟化分为 *xen-hvm* （全虚拟化）和 *xen-pv* （半虚拟化），只有前者支持更换内核。

*区分方法* ：ROOT 用户运行 ~virt-what~ 命令，若只显示 ~xen~ 则为 *xen-pv* （半虚拟化），同时显示 ~xen~ 和 ~xen-hvm~ 则为 *xen-hvm* （全虚拟化）。

* 流量的单向计算与双向计算的区别
IDC 的 VPS 流量分为 *单向计算* 与 *双向计算* 。而单向计算又分为 *只算出站流量 (VPS 上传)* 和 *VPS 上传、下载哪个流量消耗多算哪个* 。

如果你不明白是什么意思，下面举个例子：

假设 VPS 上面搭建了代理软件，然后你通过本地代理客户端下载了个 100MB 大小的文件。文件首先会下载到 VPS ，消耗 100MB 流量。接着 VPS 会把该文件上传给你，消耗 100MB 流量。

如果 VPS 的流量计算方式为：单向计算，那么后台计算的流量消耗为 100MB。
如果 VPS 的流量计算方式为：双向计算，那么后台计算的流量消耗为 200MB。
如果你买 VPS 是要搭建代理（或者 VPN、端口转发、中转），那么双向计算方式会让你的流量翻倍。

* 购买 VPS 时不要使用代理软件
如果你注册账号的时候，国家和地区填写的都是中国，但是的代理软件是其他国家（代理全局或者该 IDC 网站走代理了），导致信息不一致，很容易就被当成欺诈的而不给开通 VPS 。结果钱没了， VPS 也没了。

如果你不小心购买 VPS 时走代理导致被判断为欺诈了，可以发工单联系客服解释，也许有机会给你解封或者退款。

