#+TITLE: intellij idea 必备 plugin

- AceJump
快速跳转到屏幕某个位置（Ctrl+;）

- FindInProjectView
快捷键 F7，从editor 视图快速跳转，选定project视图中此文件

- CodeGlance
生成右侧代码缩略图，用过 Sublime 的肯定知道

- EasyShortcut
EasyShortcut 是使用IntelliJ IDEA系列开发工具中常用的快捷键介绍,查看方便,并且更容易记住快捷键. 绝对是开发必备神器,欢迎下载该插件使用,掌握这些快捷键,绝对会提高开发效率.

- Grep Console
自定义设置控制台输出颜色

- Key promoter X
快捷键提示插件，当你点击鼠标一个功能的时候，可以提示 你这个功能快捷键是什么 ，和这个按钮你的使用频率

- Maven Helper
Maven 辅助插件

- Markdown Navigator
书写 Markdown 文章

- GsonFormat
根据Gson库使用的要求,将JSONObject格式的String 解析成实体。

- FindBugs
帮你找到隐藏的bug及不好的做法。

- QAPlug

- MetricsReloaded
代码复杂度检查

- Statistic
统计代码行数

- BashSupport
Bash语言支持

- IdeaVim
vim的仿真插件

- RESTClient
模拟HTTP请求测试与服务端的通讯请求

- codota
开源代码搜索插件，使用ａｌｔ+ｋ来搜索源代码

- varname-go-die
根据中文在线查找翻译并生成指定格式的变量名称。择单词或词组后点击主菜单栏Edit → ChangeVar

- UpperLowerCapitalize
大小写转换插件,安装后快捷键alt+P全部大写     alt+L全部小写      alt+C开头字母大写

- IDETalk
神奇的东西，你可以联系局域网内其它的IDEA使用者，可以方便地把你的代码show给你的同事

- MultiHighlight
lets you highlight identifiers with custom colors (like Highlight Usages in File), it's helpful when reading source code. Ctrl+'

- Free MyBatis plugin
一款增强idea对mybatis支持的插件，主要功能如下：
生成mapper xml文件
快速从代码跳转到mapper及从mapper返回代码
mybatis自动补全及语法错误提示

- TabSwitch
通过ctrl + tab在文件，各个面板tab间切换。

- Wakatime
