MySQL 基本操作

* 目录
1 介绍
2 安装 MySQL
3 文件结构
4 进入 MySQL
5 简单的操作
6 设置远程访问
7 phpmyadmin 管理

* 介绍
是一款免费的数据库程序，为 Oracle 公司旗下产品。

* 安装 MySQL
要安装 MySQL，可以在终端提示符后运行下列命令：

sudo apt-get install mysql-server mysql-client #中途会让你输入一次 root 用户密码
sudo apt-get install php5-mysql  #安装 php5-mysql 是将 php 和 mysql 连接起来
一旦安装完成，MySQL 服务器应该自动启动。

sudo start mysql #手动的话这样启动
sudo stop mysql #手动停止
当你修改了配置文件後，你需要重启 mysqld 才能使这些修改生效。

要想检查 mysqld 进程是否已经开启，可以使用下面的命令：

pgrep mysqld
如果进程开启，这个命令将会返回该进程的 id。

* 文件结构
MySQL 配置文件：/etc/mysql/my.cnf，其中指定了数据文件存放路径

datadir         = /var/lib/mysql
如果你创建了一个名为 test 的数据库，那么这个数据库的数据会存放到 /var/lib/mysql/test 目录下。

* 进入 MySQL
** 方法一：
mysql -u root -p
(输入 mysql 的 root 密码)

qii@ubuntu:~$ mysql -u root -p
Enter password:
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 37
Server version: 5.1.41-3ubuntu12.3 (Ubuntu)

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql>
修改 MySQL 的管理员密码：

sudo mysqladmin -u root password newpassword；

** 方法二：
#+BEGIN_SRC bash
mysql --host=192.168.14.60 --user=nftest --password=daantest nftest
# or
mysql -h 192.168.14.60 -u nftest -pdaantest nftest
#+END_SRC
* 简单的操作
** Test
#+BEGIN_SRC sql
select version(), current_date;
#+END_SRC
and result is show as above
#+BEGIN_EXAMPLE
mysql> select version(), current_date;
+------------+--------------+
| version()  | current_date |
+------------+--------------+
| 5.6.16-log | 2016-10-21   |
+------------+--------------+
1 row in set (0.00 sec)
#+END_EXAMPLE

** List all databases in MySQL：
#+BEGIN_SRC sql
show databases;
#+END_SRC
...
#+BEGIN_EXAMPLE
mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mysql              |
| tutorial_database  |
+--------------------+
2 rows in set (0.00 sec)
#+END_EXAMPLE

** View Selected Database in MySQL
#+BEGIN_SRC sql
SELECT database();
#+END_SRC

Your result may be similar to this:
#+BEGIN_EXAMPLE
mysql> SELECT database();
+------------+
| database() |
+------------+
| NULL       |
+------------+
1 row in set (0.00 sec)
#+END_EXAMPLE

** Select a Database in MySQL
#+BEGIN_SRC sql
USE tutorial_database;
#+END_SRC

That command should yield a result of Database changed similar to:
#+BEGIN_EXAMPLE
mysql> USE tutorial_database;
Database changed
#+END_EXAMPLE

** List all tables in selected database
#+BEGIN_SRC sql
show tables;
#+END_SRC
...
#+BEGIN_EXAMPLE
mysql> show tables;
+-----------------------------+
| Tables_in_tutorial_database |
+-----------------------------+
| employee                    |
+-----------------------------+
#+END_EXAMPLE

* 设置远程访问
1.取消本地监听
正常情况下，mysql 占用的 3306 端口只是在 IP 127.0.0.1 上监听，
拒绝了其他 IP 的访问（通过 netstat 可以查看到）。
取消本地监听需要修改 my.cnf 文件：

sudo vim /etc/mysql/my.cnf
//找到如下内容，并注释
bind-address = 127.0.0.1
然后需要重启 mysql（可最后再重启）。

2.授权法

mysql>GRANT ALL PRIVILEGES ON *.* TO <user>@"%" IDENTIFIED BY '<password>' WITH GRANT OPTION;
mysql>FLUSH PRIVILEGES
第二句表示从 mysql 数据库的 grant 表中重新加载权限数据。因为 MySQL 把权限都放在了 cache 中，所以在做完更改后需要重新加载。

* phpmyadmin 管理
用随便一个支持 PHP 的 web 服务器（如 Apache、Nginx、Lighttpd），下载 phpmyadmin，装之。

sudo apt-get install phpmyadmin  #注意这是安装到/usr/share/phpmyadmin
