#+TITLE: manjaro 安装好之后的配置

* 如何更换和添加源

软件仓库（在 Debian 系发行版中，又叫做“软件源”）是软件包存储的地方。通常我们所说的软件仓库指在线软件仓库，亦即用户从互联网获取软件的地方。

** 手动选择软件仓库镜像
@see https://blog.yoitsu.moe/arch-linux/installing_arch_linux_for_complete_newbies.html
用 nano 打开 /etc/pacman.d/mirrorlist

sudo nano /etc/pacman.d/mirrorlist

最简单的方法还是把下面那些 Mirrors 先全删掉然后输入一个新的，用光标指向某一行以后同时按下 Ctrl+K 就好。
然后自己输入一个 Mirror，下面给出几个中国国内的 Mirror：

## Country : China
# 清华大学 TUNA 协会
Server = http://mirrors.tuna.tsinghua.edu.cn/manjaro/stable/$repo/$arch
# Server = https://mirrors.tuna.tsinghua.edu.cn/archlinux/$repo/os/$arch

## Country : China
# 中国科学技术大学
Server = https://mirrors.ustc.edu.cn/manjaro/stable/$repo/$arch
# Server = https://mirrors.ustc.edu.cn/archlinux/$repo/os/$arch

## Country : China
Server = https://mirrors.zju.edu.cn/manjaro/stable/$repo/$arch

## Country : China
Server = https://mirrors.shuosc.org/manjaro/stable/$repo/$arch

## Country : Hong_Kong
Server = http://ftp.cuhk.edu.hk/pub/Linux/manjaro/stable/$repo/$arch


然后用 pacman -Syy 刷新一下软件包数据库。

root@archiso ~ # pacman -Syy
:: Synchronizing package databases...
core                                  120.9 KiB  4.92M/s 00:00 [##################################] 100%
extra                                1755.6 KiB  5.24M/s 00:00 [##################################] 100%
community                               3.7 MiB  6.82M/s 00:01 [##################################] 100%
root@archiso ~ #

** 自动选择软件仓库镜像
1.1.
sudo nano /etc/pacman.d/mirrors/China
manjaro 17 中 China 文件已经内置了中国的源，建议把清华的源镜像放在第一位，也可以不做更改

1.2.
sudo nano /etc/pacman.d/mirrorlist
建议把清华的源镜像放在第一位，更新列表和系统的时候速度会快，也可以不做更改

调整镜像列表

1.3.
sudo nano /etc/pacman-mirrors.conf
修改 OnlyCountry = China（注意把前面的注释 # 删掉）

修改 OnlyCoutntry = China
保存退出

1.4.
sudo nano /etc/pacman.conf
文末添加

[archlinuxcn]
SigLevel = Optional TrustedOnly
Server = https://mirrors.ustc.edu.cn/archlinuxcn/$arch

sudo pacman -Syy
sudo pacman -S archlinuxcn-keyring

1.5.
排列源(在终端输入）：
sudo pacman-mirrors -g
然后同步：
sudo pacman-optimize && sync
升级系统：
sudo pacman -Syyu

Tips：注意第二步会对固态硬盘出现问题。

** AUR 镜像
修改 /etc/yaourtrc，去掉 # AURURL 的注释，修改为

AURURL="https://aur.tuna.tsinghua.edu.cn"

** ArchlinuxCN 镜像
@See https://github.com/archlinuxcn/repo

Arch Linux 中文社区仓库 是由 Arch Linux 中文社区驱动的非官方用户仓库。包含中文用户常用软件、工具、字体/美化包等。

完整的包信息列表（包名称/架构/维护者/状态）请 点击这里 查看。

 官方仓库地址：http://repo.archlinuxcn.org
 镜像地址: https://mirrors.tuna.tsinghua.edu.cn/archlinuxcn/
使用方法：在 /etc/pacman.conf 文件末尾添加以下两行：

[archlinuxcn]
Server = https://mirrors.tuna.tsinghua.edu.cn/archlinuxcn/$arch

之后安装 archlinuxcn-keyring 包导入 GPG key。
sudo pacman -Syy && sudo pacman -S archlinuxcn-keyring


* 安装后更新系统

在终端输入以下命令更新系统

sudo pacman -Syy
sudo pacman -Syu


* 在 Manjaro 中安装卸载软件：
（1）在设置里找到添加/删除软件，打开：
[./images/install-software.jpg]

这是 xfce 下软件管理器，kde 下有点不同，但大同小异。你可以在左上搜索框中输入要搜索的软件，
勾选并应用就可以安装，还可以启用 AUR 搜索，如图：
[./images/install-software-2.jpg]

（2）通过命令安装/卸载软件：
安装软件命令（package_name 即是指软件名字，如 firefox）：
pacin package_name

卸载软件命令：
pacre package_name

卸载软件＋不需要的依赖（类似 sudo apt autoremove）：
sudo pacman -Rs package_name


* 设置基本系统

** 基本中文支持
@See https://wiki.archlinux.org/index.php/Arch_Linux_Localization_(%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87)

*** /etc/locale.gen
是一个仅包含注释文档的文本文件。指定您需要的本地化类型，去掉对应行前面的注释符号（＃）就可以啦，
还是用 nano 打开，建议选择帶 UTF-8 的項：
# nano /etc/locale.gen

en_HK.UTF-8 UTF-8
en_US.UTF-8 UTF-8
zh_CN.UTF-8 UTF-8
zh_HK.UTF-8 UTF-8
zh_TW.UTF-8 UTF-8

*** 执行 locale-gen 以生成 locale 讯息：
# locale-gen

Generating locales...
  en_US.UTF-8... done
  zh_CN.UTF-8... done
  zh_HK.UTF-8... done
  zh_TW.UTF-8... done
Generation complete.

*** locale.conf
将系统 locale 设置为 en_US.UTF-8，系统的 Log 就会用英文显示，这样更容易问题的判断和处理。用户可以设置自己的 locale。
警告: 不推荐在此设置任何中文 locale，或导致 tty 乱码。
用文字编辑器 zai 这个文件 zhon 加上这一行。

LANG=en_US.UTF-8

or:

# echo 用来输出某些文字，后面的大于号表示把输出保存到某个文件里啦~
# 或者可以用文字编辑器新建这个文件加上这一行。
echo LANG=en_US.UTF-8 > /etc/locale.conf

*** 安装中文字体

- Google Noto Fonts 系列：noto-fonts noto-fonts-cjk noto-fonts-emoji
- 思源黑体：adobe-source-han-sans-otc-fonts (adobe-source-han-sans-cn-fonts , adobe-source-han-sans-tw-fonts)
- 文泉驿：wqy-microhei wqy-zenhei

更多的字体可以在 https://wiki.archlinux.org/index.php/Fonts_(简体中文) 找到。

pacin ttf-hack
pacin wqy-zenhei wqy-microhei

# adobe 字体全家桶：
pacin adobe-source-code-pro-fonts
pacin adobe-source-sans-pro-fonts
pacin adobe-source-serif-pro-fonts
pacin adobe-source-han-sans-cn-fonts
pacin adobe-source-han-serif-cn-fonts

*** 安装中文输入法
@See https://wiki.archlinux.org/index.php/fcitx#Chinese

以安装 googlepinyin 为例

pacin fcitx-googlepinyin
pacin fcitx-im
pacin fcitx-configtool # 图形化的配置工具

保存成功后，注销重新登陆系统，在终端输入 fcitx 启动服务，就能切换 googlepinyin 了。

** 设置时区（中国的时区是 Asia/Shanghai）
# ln -s <源文件> <目标> 创建一个符号链接

# ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

** 设置时间标准 为 UTC，并调整 时间漂移:
# hwclock --systohc
[Fail]

** 时间同步

用 timedatectl set-ntp true 保证时间同步 。

root@archiso ~ # timedatectl set-ntp true
root@archiso ~ # timedatectl status
    Local time: Fri 2016-10-28 17:39:42 UTC
Universal time: Fri 2016-10-28 17:39:42 UTC
        RTC time: Fri 2016-10-28 17:39:42
    Time zone: UTC (UTC, +0000)
Network time on: yes
NTP synchronized: yes
RTC in local TZ: no

** 设置一个喜欢的主机名（用汝的主机名代替 myhostname）：
# echo myhostname > /etc/hostname

** 设置 root 的密码（输入密码的时候就是啥也没有 ╮(￣▽￣)╭ ）：
[root@archiso /]# passwd
New password:
Retype new password:
passwd: password updated successfully


* 安装 zsh，及 oh-my-zsh 的配置

** 安装 zsh
# 最新版本已经默认安装了。
sudo pacman -S zsh

** 安装 oh-my-zsh
# 安装 oh-my-zsh
sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

# 更换默认的 shell
chsh -s $(which zsh)

# 查看当前 shell
echo $SHELL

# 查看本地有哪几种 shell
cat /etc/shells

# 开启 archlinux 插件
plugins=(archlinux)

** 安装 zsh theme
mkdir $ZSH_CUSTOM/themes
git clone https://github.com/denysdovhan/spaceship-prompt.git "$ZSH_CUSTOM/themes/spaceship-prompt"
ln -s "$ZSH_CUSTOM/themes/spaceship-prompt/spaceship.zsh-theme" "$ZSH_CUSTOM/themes/spaceship.zsh-theme"

# 更换默认的 shell 提示符
# random bira blinks fino gnzh rkj-repos tjkirch xiong-chiamiov-plus ys spaceship
ZSH_THEME="spaceship"


* 安装 theme
https://github.com/horst3180/Arc-theme
pacin arc-gtk-theme


* 安装驱动程序

** Intel CPU 安装 Intel-ucode
@See https://wiki.archlinux.org/index.php/Microcode

非 IntelCPU 可以跳过此步骤。
直接 pacman 安装：

pacman -S intel-ucode

** 显卡驱动
Archlinux 中的显卡驱动都是以 xf86-video 开头的。

Archlinux 中列出所有的 PCI 设备：
$ lspci

查询显卡类型：
$ lspci | grep VGA

查询可用的开源驱动：
$ pacman -Ss xf86-video | less

发现 xf86-video-intel 是 Intel 显卡的驱动，安装之。

- 物理机安装 Intel 核心显卡驱动（intel）：
$ pacman -S xf86-video-intel

- 虚拟机安装通用驱动（vesa）：
$ pacman -S xf86-video-vesa
支持硬件加速的驱动程序可以在安装 X 时自动提示你安装，只需要选择正确的显卡类型，不需要显式安装。

** 配置双屏
@See http://blog.ggshiney.com/posts/2012/11/14/config-dual-monitor-for-archlinux.html

显卡驱动就绪后两个显示器显示相同，如果需要扩展显示桌面，还需要进行一番配置。

randr(X Resize, Rotate and Reflect Extension)可以控制桌面的显示输出效果，如镜像、旋转等。xrandr 是 randr 的命令行接口。
安装 xrandr
$ pacman -S xorg-xrandr

首先查看当前显示状态，列出目前環境支援的解析度和頻率：
xrandr -q

看到我的两个显示器对应着 DP1 和 DP3，接下来设置两个显示器位置：
xrandr --output DP1 --auto --output DP3 --auto --right-of DP1

** 自动启动
可以把通过这条命令预览好的位置，加入配置文件 /etc/X11/xorg.conf.d/10-monitor.conf，以实现自动启动。

Section "Monitor"
    Identifier  "DP3"
    Option      "Primary" "true"
EndSection

Section "Monitor"
    Identifier  "DP1"
    Option      "LeftOf" "DP3"
EndSection


* 其他美化

** 设置pacman彩色输出
打开 /etc/pacman.conf 文件，找到被注释的 #Color，改为 Color。pacman 就会输出彩色信息，方便查看。


* 安装一些工具

** linux-headers
pacman -S linux-headers

** inotify-tools
pacman -S inotify-tools

** net tools
ifconfig, route 在 net-tools 中，
nslookup, dig 在 dnsutils 中，
ftp, telnet 等在 inetutils 中,
ip 命令在 iproute2 中。

pacman -S net-tools dnsutils inetutils iproute2

** yaourt
Yaourt 是 archlinux 方便使用的关键部件之一，但没有被整合到系统安装中的工具。
建议在装完系统重启之后，更新完 pacman 和基本系统之后，就安装这个工具。

以 root 权限打开编译/etc/pacman.conf，将下面这三行加入到文件末尾并保存：

[archlinuxcn]
SigLevel = Never
Server   =  http://repo.archlinuxcn.org/$arch
同步软件信息库并安装 yaourt：

pacman -S yaourt

配置 AUR 镜像：修改 /etc/yaourtrc，去掉 # AURURL 的注释，修改为

AURURL="https://aur.tuna.tsinghua.edu.cn"

参考：
https://mirrors.tuna.tsinghua.edu.cn/help/AUR/

yaourt -Syua

** google-chrome
在上一步安装了 yaourt 之后，就可以安装 google-chrome 了
yaourt -S google-chrome

** 下载代理插件 Proxy SwitchyOmega
chrome 扩展商店的地址在这里：
https://chrome.google.com/webstore/detail/proxy-switchyomega/padekgcemlokbadohgkifijomclgjgif

同样提供另外的地址：
http://pan.baidu.com/s/1slrU97B

** shadowsocks-libev
@See https://github.com/madeye/shadowsocks-libev#usage
sudo pacman -S shadowsocks-libev

** Sublime text 3

/opt/text/sublime_text_3

ln -s /opt/text/sublime_text_3/sublime_text /usr/local/bin/sublime_text

** emacs 25.3
@See build-emacs.sh

** percol
pacin percol

** 远程桌面连接 windows

*** remmina
pacman -S remmina

*** rdesktop
pacman -S rdesktop

rdesktop 连接 windows 远程桌面
打开命令行，仅需要一条命令：
rdesktop -f -u username -p password IP -r sound:on/off -g 1024*768

说明：
1、username 和 password 分别是目标电脑的帐号和密码，-a 16 表示位色，最高就是 16 位；
2、IP 为目标电脑的 IP 地址（可能需要先连接 VPN）；
3、sound：on 表示传送目标电脑的声音，off 则为关闭；
4、-g 后接想要显示的分辨率，使用 -g workarea 可自适应铺满当前 linux 窗口大小
5、-f 参数默认全屏打开，使用 Ctrl + Alt + Enter 可以退出全屏模式（不知道的就郁闷了）。
6、-r** disk:share_name=/local-disk** 将本地磁盘映射到远程电脑，其中 share_name 为显示名称，可自定义，local-disk 表示本地 linux 的一个目录，比如 /data。
7、-r clipboard:PRIMARYCLIPBOARD 允许在远程主机和本机之间共享剪切板，就是可以复制粘贴。

比如如下命令：

$ rdesktop -f -u administrator -p ncl@2017.com 192.168.2.160
这里的 ip 对应远程 windows 的 ip 地址

如果不想每次都敲命令的，可以简单的写个 shell 脚本，每次点击就可以连接。

** Tencent QQ
提供在 Linux 上运行最新版腾讯 QQ 与 TIM 的解决方案：
https://github.com/askme765cs/Wine-QQ-TIM

** 虚拟机
有些时候需要使用 windows 而不想切换系统或干脆没有 windows 的情况下，我们可以使用 windows 虚拟机来代替。当然虚拟机的用处不止于此。

Arch 下的虚拟机首先开源的 VirtualBox，安装官方源的 virtualbox virtualbox-ext-vnc virtualbox-guest-iso virtualbox-host-modules-arch 这几个包。

再去官网下载 Oracle VM VirtualBox Extension Pack，在设置中导入使用。
安装 windows 的过程不在这里讲解，记得安装之后在 windows 内安装扩展客户端软件即可。
