#+TITLE: Manjaro文件结构和分区方案

@See https://blog.csdn.net/fan_xiao_hui/article/details/104115227

* 文件结构
Linux不同文件夹的功能：[[https://www.cnblogs.com/zhuchenglin/p/8686924.html][详细内容]]

 - bin目录：许多“指令”对应的可“执行程序文件”目录
 - sbin目录："root"用户可以执行的指令普通用户不能使用该目录里的命令
 - usr目录：unix system resource (unix系统资源文件目录)，经常用于安装各种软件
 - dev目录：系统硬件设备目录
 - home目录：普通用户的“家目录”
 - proc目录：内存映射目录，该目录可以查看系统的相关信息
 - var目录：该目录存储的文件经常会发生变化（增加、修改、删除）。例如：/var/www/shop
 - boot目录：系统启动核心目录，用于储存系统启动文件
 - etc目录：系统主要配置文件目录
 - lib目录：系统资源文件类库目录
 - tmp目录：存放临时文件的目录
 - mnt目录：存放临时的映射文件系统。我们常把软驱和光驱挂装在这里的floppy和cdrom子目录下。

* 分区方案
用途不同，喜好不同， 分区方案不同。因此不存在最佳的分区方案_

** 1. 简单方案
*** 一个“/”分区， 一个“swap”分区。

“/”分区(root分区)相当于windows系统中的C盘；而“swap”分区相当于虚拟内存。

运存 < 4GB，swap空间 = 运存大小*2
4GB < 运存 < 16GB，swap空间 = 运存大小
运存 > 16GB，swap空间 = 4G，最好不要为0

*** 一个“/”分区， 一个"/boot"分区，一个“swap”分区。

“/boot”分区(引导分区)：
不使用 UEFI 时，/boot 的建议大小时 200 MB，使用 UEFI 时，需要 512 MiB 空间。

把该分区单分出来，若“/”分区(root分区)出现了问题，计算机依然能够启动。

** 2. 常用方案
众所周知，Linux的文件系统是一种树状的结构，一个软件在安装的过程中会把不 同的文件根据不同的使用目的分别放置在不同的目录当中。因此，系统中每个目录扩张的速度会不一样。尽管不分区一起使用”/“的空间，会有最好的空间使用效率，但这样容易造成系统不稳定，或其它的问题的情形发生。

 - /bin，/sbin，/lib，/etc，/dev 这五个目录绝对不可与"/"所在的分区分开。
 - /cdrom，/mnt，/media，/proc，/run，/sys，/srv等目录可以放到其它的分区，但不需要。
 - /home，/var，/usr最好（并非「必要」）与根目录分开，到其它分区的目录。

/home分区，主要存放用户数据。这样就可以在不删除用户数据文件的情况下升级或重新安装。
/var分区，主要放置系统执行过程中经常变化的文件，例如缓存（cache）或者是随时更改的登录文件（log file）。
/usr分区，Linux系统存放软件的地方，如有可能应将最大空间分给它。 （manjaro规定”/usr“不应该单独分区）

* 分区示例
我160G的硬盘，"/boot"为500MB，“swap"为4GB，”/root"为15GB，"/var"为60GB，剩余空间为"/home"。

