EMACS 常用操作
=============


朝气蓬勃社  2014 年 12 月 15 日
--------------------------


这是本社整理的有用且常用的已卖克斯（Emacs）纯文本编辑器命令。如果谁有
兴趣，请将它翻译成中文，以飨不懂英文的同学。总体感觉已卖克斯功能强大的
代价就是太复杂，不如记事本那样即开即用老少咸宜。所以，我不建议大家使用
这个软件，即使你是专业写程序的。如果 99%的时间所做的事情记事本都能做到，
为什么要浪费时间学一个编辑器呢？已卖克斯自带的计算器，日历，文件目录浏
览，文件对比，版本管理，远程编辑等完全有其他更好的软件或方案可以替代。
减去学习使用的时间后，已卖克斯所能提高的效率并没有想象的那么高。当然，
已经会用的同学，继续用坏处肯定没有。


* Emacs useful commands *



C       stands for Ctrl key.
M       stands for Alt key.
C-x     stands for pressing Ctrl and x at the same time.
M-x     stands for pressing Alt and x at the same time.
C-M     stands for pressing Ctrl and Alt at the same time.
C-x C-f stands for pressing Ctrl and x at the same time, then pressing Ctrl and f at the same time.
C-M-a   stands for pressing Ctrl, Alt and a at the same time.


emacs &              open emacs
emacs -nw            open emacs in terminal
emacs -nw a.txt      open a.txt using emacs in terminal


For all text files
------------------

C-x C-f              open a file
C-x C-w              save as
C-x C-s              save a file
C-x s                save all opened files
C-x k                close a file
M-x pwd              path of a file
C-x b                switch between current file and previous file
C-x C-b              list all opened files in another window

C-x o                move cursor to another window
C-x 2                split window up-down
C-x 3                split window left-right
C-x {                change size of window
C-x }                change size of window
C-x ^                make window taller
C-x 4 f              open file in another window
C-x 4 d              open directory in another window
C-x 0                close this window
C-x 1                close other windows

C-x C-c              exit emacs
C-z                  suspend emacs

C-p                  go up one line, or up arrow key
C-n                  go down one line, or down arrow key
C-a                  go to beginning of a line
C-e                  go to end of a line
C-u 5 C-p            go up 5 lines
C-u 5 C-n            go down 5 lines
M-a                  go the beginning of a sentence
M-e                  go the end of a sentence
M-{                  go up one paragraph
M-{                  go down one paragraph
C v                  go to next page
M v                  go to previous page
M-<                  go to beginning of a file
M->                  go to end of a file

C-f                  go forward one character, or right arrow key
C-b                  go backward one character, or left arrow key
M-f                  go forward one word
M-b                  go backward one word

C-d                  delete a character
M-d                  delete a word forward
C-BACKSPACE          delete a word backward. BACKSPACE key.
C-k                  delete a line
M-k                  delete everything after cursor and before .
M-z                  delete everything after cursor and before a character
M-\                  delete white spaces around a cursor
M-SPACE              delete white spaces around a cursor, remaining one space
C-x C-o              delete blank lines

M-c                  capitalize the first character of a word
M-u                  capitalize a whole word
M-l                  make a whole word lower-case
C-x C-u              capitalize a selected area
C-x C-l              make a selected area lower-case
C-t                  exchange positions of two characters
M-t                  exchange positions of two words
C-x C-t              exchange positions of two lines
M-x transpose-paragraphs  exchange two paragraphs

M-q                  indent a paragraph
M-h                  select a paragraph
C-x h                select entire file
C-@                  set a mark for starting of an area
C-SPACE              same as C-@. SPACE stands for Space key.
M-w                  copy a selected area
C-w                  cut a selected area
C-y                  pasted most recently copied area
C-u 2 C-y            pasted last 2 copied area
C-/                  undo edit (should use this)
C-o                  insert blank lines after cursor's position
C-x i                insert another file into current file

M-x goto-line        go to a line, or M-g g
C-s                  forward search a string
C-r                  backward search a string
M-p                  previous search string
M-n                  next search string

C-x ESC ESC          edit and repeat last command
M-r                  search commands
M-s                  search commands

M-%                  query replace a string
n                    don't replace this one, go to next match
,                    replace this one and stop
!                    replace everything from here

C-M-%                regular expression query replace (not comfortable)
C-M-s                regular expression search
C-M-r                reverse regular expression search

C-x r m              set a bookmark
C-x r b              jump to a bookmark
C-x r l              list all bookmarks

M-x what-page        page number and line number

M-x dired            open directory
g                    update subdirectories
i                    see files in a subdirectory.  move cursor to there first.
+                    create a directory
n                    go to next file
p                    go to previous file
v                    view a file
f                    open the file for editing
d                    mark a file as delete
m                    mark a file
u                    undo mark
* !                  unmark all files in this folder
x                    delete a file
o                    open a file in another window
% d                  mark files matching a regexp as delete
% m                  mark files matching a regexp with *
* s                  mark all files
% g                  mark files whose contents matching a regexp with *
C-/                  undo changes in the directory
R                    rename a file
C                    copy  file(s)
Z                    compress or uncompress a file
A                    search all marked files
M-,                  continue search
Q                    query replace search on all marked files


Cool stuff: replace all "aa" with "bb" in all .txt files in all subdirectories
------------------------------------------------------------------------------
1. M-x find-dired
   -name "*.txt" -print
2. % s  (mark all files found)
3. Q    (start replacing)


Cool stuff: recursively grep into all subdirectories
----------------------------------------------------
1. M-!
2. grep -r pattern directory
(use grep -l -r pattern directory to list matching files only)


Cool stuff: find files and do word count for all of them
--------------------------------------------------------
1. M-!
2. find . -name "*.txt" -print | xargs -l -i wc {}

M-x occur            similar as grep

M-x ispell-buffer    spelling check a file
M-$                  spelling check a word
C-x z                repeat the previous command
M-x column-number-mode show column number

M-x calendar         check calendar
q                    close calendar

M-/                  automatically complete a word (cool)
M-!                  execute a shell command
M-x shell            start a new shell
M-p                  see previous comand
M-n                  see next command

C-u 20 L             write 20 L's

For C source code
-----------------

C-M-a               go to beginning of a function
C-M-e               go to end of a function
C-M-h               select a function
M-;                 insert /* */

C-c C-q             indent a whole funtion
M-x imenu           show all function names
M-x which-function-mode show which function I am in

M-x hs-minor-mode   enter a mode that can hide bodies of functions
M-x hs-hide-all     hide all bodies of functions
M-x hs-show-all     show all bodies of functions

C-M-t               exchange things around '='

M-x recover-file    recover a file lost during system crash


Rectangle operations
--------------------

C-x r o            open a rectangle
C-x r c            clear a rectangle
C-x r k            kill a rectangle
C-x r y            paste a rectangle
C-x r r            copy a rectangle to register
C-x r i            paste the rectangle


Select theme
------------
M-x load-theme


No line wrap
------------
M-x toggle-truncate-lines


Help
----
C-h a             show commands matching a string
C-h b             show key bindings


Paste 100 times
---------------

C-x ( C-y C-u 100 C-x )


.emacs config
-------------

;; Disable backup files
(setq backup-inhibit t)
(setq auto-save-default nil)
(setq make-backup-files nil)
(setq make-autosave-files nil)

;; Inhibit startup message
(setq inhibit-startup-message t)


安装其他包（2015-04-27 更新）
-------------------------

有时候需要安装一些工具包。需要以下几步操作。

第一步. 在.emacs 中，设置包源。插入下面代码。

(require 'package)
(add-to-list 'package-archives
             '("melpa" . "http://melpa.org/packages/") t)
(when (< emacs-major-version 24)
  ;; For important compatibility libraries like cl-lib
  (add-to-list 'package-archives '("gnu" . "http://elpa.gnu.org/packages/")))
(package-initialize)


第二步. 列出所有可以按照的包

M-x list-packages


第三步. 光标停在要安装的包名, 敲 i, 然后敲 x


第四步. 可能还需要在.emacs 中加一行。具体见包的安装手册。

(require 'xxxx)
xxxx 是包名

我用以上方式安装了 material-theme 和 zen-and-art 主题。
也可以安装 ace-window，方便多框情况下在各个框之间切换，用 Alt 和 p 组合键。


■ 常用设置 ■

;; 中文用雅黑/宋体显示
;;(set-fontset-font "fontset-default" 'gb18030 '("Microsoft YaHei" . "unicode-bmp"))
(set-fontset-font "fontset-default" 'gb18030 '("SimSun" . "unicode-bmp"))


--
最后更新: 2015-11-12
