#+TITLE:Python tutorial 2.7.11

@See http://www.pythondoc.com/pythontutoial27/index.html

* 1.开胃菜
Python 是一门解释型语言，因为无需编译和链接。
* 2. 使用 Python 解释器
** 2.1. 调用 Python 解释器
#+BEGIN_SRC bash
python
#+END_SRC
输入 quit() 命令退出解释器。
*** 2.1.1. 参数传递
调用解释器时，脚本名和附加参数传入一个名为 sys.argv 的字符串列表。你能够通过执
行 import sys 来获取这个列表
*** 2.1.2. 交互模式
主提示符通常标识为三个大于号 (>>>)；从属提示符，由三个点标识 (...)。
** 2.2. 解释器及其环境
*** 2.2.1. 源程序编码
在 Python 源文件中可以使用非 ASCII 编码。最好的方法是在 #! 行的后面再增加一行特
殊的注释来定义源文件的编码:
#+BEGIN_SRC python
# -*- coding: encoding -*-
#+END_SRC
通过此声明，源文件中所有的东西都会被当做用 encoding 指代的 UTF-8 编码对待。
在 Python 库参考手册 [[https://docs.python.org/2.7/library/codecs.html#module-codecs][codecs]] 一节中你可以找到一张可用的编码列表。
* 3. Python 简介
Python 中的注释以 # 字符起始，直至实际的行尾
** 3.1. 将 Python 当做计算器
*** 3.1.1. 数字
解释器表现得就像一个简单的计算器：可以向其录入一些表达式，它会给出返回值。
表达式语法很直白：运算符 +，-，* 和 / ；括号 ( () ) 用于分组。
整数的类型是 int，带有小数部分的数字的类型是 float。

除法 ( / ) 返回的类型取决于它的操作数。
如果两个操作数都是 int，将采用 floor division 除法并返回一个 int。
如果两个操作数中有一个是 float，将采用传统的除法并返回一个 float。
还提供 // 运算符用于 floor division 而无论操作数是什么类型。
余数可以用 % 操作符计算。
使用 ** 运算符计算幂乘方。

等号( '=' )用于给变量赋值。
变量在使用前必须 “定义”(赋值)，否则会出错。

浮点数有完整的支持；与整型混合计算时会自动转为浮点数。

交互模式中，最近一个表达式的值赋给变量 _。
此变量对于用户是只读的。不要尝试给它赋值

除了 int 和 float，Python 还支持其它数字类型，例如 Decimal 和 Fraction。
Python 还内建支持 复数 ，使用后缀 j 或 J 表示虚数部分（例如，3+5j）。

*** 3.1.2. 字符串
可以通过几种不同方式表示的字符串。
它们可以用单引号 ('...') 或双引号 ("...") 标识。

\ 可以用来转义引号。

在交互式解释器中，输出的字符串会用引号引起来，特殊字符会用反斜杠 (\) 转义。
如果你前面带有 \ 的字符被当作特殊字符，你可以使用“原始字符串”，方法是在第一个
引号前面加上一个 r。

字符串文本能够分成多行。一种方法是使用三引号："""...""" 或者 '''...'''。
行尾换行符会被自动包含到字符串中，但是可以在行尾加上 \ 来避免这个行为。
也就是说：以反斜杠为行结尾的字符串，它表示下一行在逻辑上是本行的后续内容。

字符串可以由 + 操作符连接(粘到一起)，可以由 * 表示重复。

Python 没有单独的字符类型；一个字符就是一个简单的长度为 1 的字符串。

字符串也可以被检索。类似于 C，字符串的第一个字符索引为 0。
索引也可以是负数，这将导致从右边开始计算。
切片的索引有非常有用的默认：
值省略的第一个索引默认为零，省略的第二个索引默认为切片的字符串的大小。
试图使用太大的索引会导致错误。

除了索引，还支持 切片。索引用于获得单个字符，切片 让你获得一个子字符串。
包含起始的字符，不包含末尾的字符。
Python 能够优雅地处理那些没有意义的切片索引：
一个过大的索引值(即下标值大于字符串实际长度)将被字符串实际长度所代替，
当上边界比下边界大时(即切片左值大于右值)就返回空字符串。

Python 字符串不可以被更改 — 它们是 不可变 的。

内置函数 len() 返回字符串长度。

*** 3.1.3. 关于 Unicode
从 Python2.0 起，程序员们有了一个新的用来存储文本数据的类型：Unicode 对象。
Unicode 的先进之处在于为每一种现代或古代使用的文字系统中出现的每一个字符都提供
了统一的序列号。
在 Python 中创建 Unicode 字符串和创建普通的字符串一样简单:
#+BEGIN_SRC python
>>> u'Hello World !'
u'Hello World !'
#+END_SRC
引号前的 'u' 表示这会创建一个 Unicode 字符串。

Python 提供了基于已知编码来创建 Unicode 字符串的整套方法。
内置函数 unicode() 可以使用所有注册的 Unicode 编码(COders 和 DECoders)。
如果有一个其它编码的数据，希望可以从中生成一个 Unicode 字符串，你可以使用
unicode 函数，它接受编码名作为第二参数。
*** 3.1.4. 列表
Python 有几个 =复合= 数据类型，用于表示其它的值。最通用的是 =list (列表)= ，
它可以写作中括号之间的一列逗号分隔的值。列表的元素不必是同一类型。

列表可以被索引和切片。
所有的切片操作都会返回一个包含请求的元素的新列表。
+ 操作可以连接多个列表。
列表允许修改元素。
可以使用 append() 方法在列表的末尾添加新的元素。
也可以对切片赋值，此操作可以改变列表的尺寸，或清空它。

内置函数 len() 同样适用于列表。

允许嵌套列表(创建一个包含其它列表的列表)。
** 3.2. 编程的第一步
在 Python 中，任何非零整数都是 true；0 是 false。
判断条件也可以是字符串或列表，实际上可以是任何序列；
所有长度不为零的是 true，空序列是 false。

标准比较操作符与 C 相同：<、>、==、<=、>= 和 !=。

缩进是 Python 组织語句的方法。
同一个语句块中的每一行必须缩进同样数量的空白。
* 4. 深入 Python 流程控制
** 4.1. if 语句
例如:
#+BEGIN_SRC python
>>> x = int(raw_input("Please enter an integer: "))
Please enter an integer: 42
>>> if x < 0:
...      x = 0
...      print 'Negative changed to zero'
... elif x == 0:
...      print 'Zero'
... elif x == 1:
...      print 'Single'
... else:
...      print 'More'
...
More
#+END_SRC
可能会有零到多个 elif 部分，else 是可选的。
** 4.2. for 语句
Python 的 for 语句依据任意序列(链表或字符串)中的子项，按它们在序列中的顺序来进
行迭代。

例如:
#+BEGIN_SRC python
>>> # Measure some strings:
... words = ['cat', 'window', 'defenestrate']
>>> for w in words:
...     print w, len(w)
...
cat 3
window 6
defenestrate 12
#+END_SRC

在迭代过程中修改迭代序列不安全。如果你想要修改你迭代的序列(例如：复制选择项)，
你可以迭代它的复本。使用切割标识就可以很方便地做到这一点:
#+BEGIN_SRC python
>>> for w in words[:]:  # Loop over a slice copy of the entire list.
...     if len(w) > 6:
...         words.insert(0, w)
...
>>> words
['defenestrate', 'cat', 'window', 'defenestrate']
#+END_SRC
** 4.3. range() 函数
如果你需要一个数值序列，内置函数 range() 会很方便，它生成一个等差级数链表:
#+BEGIN_SRC python
>>> range(10)
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
#+END_SRC

也可以让 range 操作从另一个数值开始，或者可以指定一个不同的步进值(甚至是负数，
有时这也被称为 “步长”):
#+BEGIN_SRC python
>>> range(5, 10)
[5, 6, 7, 8, 9]
>>> range(0, 10, 3)
[0, 3, 6, 9]
>>> range(-10, -100, -30)
[-10, -40, -70]
#+END_SRC

需要迭代链表索引的话，如下所示结合使用 range() 和 len():
#+BEGIN_SRC python
>>> a = ['Mary', 'had', 'a', 'little', 'lamb']
>>> for i in range(len(a)):
...     print i, a[i]
...
0 Mary
1 had
2 a
3 little
4 lamb
#+END_SRC
** 4.4. break 和 continue 语句, 以及循环中的 else 子句
=break= 语句和 C 中的类似，用于跳出最近的一级 for 或 while 循环。

循环可以有一个 else 子句；它在循环迭代完整个列表 (对于 for) 后或执行条件为
false (对于 while) 时执行，但循环被 break 中止的情况下不会执行。

=continue= 语句是从 C 中借鉴来的，它表示循环继续执行下一次迭代。
** 4.5. pass 语句
=pass= 语句什么也不做。它用于那些语法上必须要有什么语句，但程序什么也不做的场合。
另一方面，pass 可以在创建新代码时用来做函数或控制体的占位符。可以让你在更抽象的
级别上思考。
** 4.6. 定义函数
我们可以定义一个函数用来生成任意上界的菲波那契数列:
#+BEGIN_SRC python
>>> def fib(n):    # write Fibonacci series up to n
...     """Print a Fibonacci series up to n."""
...     a, b = 0, 1
...     while a < n:
...         print a,
...         a, b = b, a+b
...
>>> # Now call the function we just defined:
... fib(2000)
0 1 1 2 3 5 8 13 21 34 55 89 144 233 377 610 987 1597
#+END_SRC

关键字 =def= 引入了一个函数 定义 。在其后必须跟有函数名和包括形式参数的圆括号。
函数体语句从下一行开始，必须是缩进的。

函数体的第一行语句可以是可选的字符串文本，这个字符串是函数的文档字符串，或者称
为 docstring。在你的代码中包含 docstrings 是一个好的实践。

函数 =调用= 会为函数局部变量生成一个新的符号表。确切地说，所有函数中的变量赋值
都是将值存储在局部符号表。变量引用首先在局部符号表中查找，然后是包含函数的局部
符号表，然后是全局符号表，最后是内置名字表。

一个函数定义会在当前符号表内引入函数名。函数名指代的值(即函数体)存在一个被
Python 解释器认定为 用户自定义函数 的类型。这个值可以赋予其他的名字(即变量名)，
然后它也可以被当做函数使用。这可以作为通用的重命名机制:
#+BEGIN_SRC python
>>> fib
<function fib at 10042ed0>
>>> f = fib
>>> f(100)
0 1 1 2 3 5 8 13 21 34 55 89
#+END_SRC

以下示例演示了如何从函数中返回一个包含菲波那契数列的数值链表，而不是打印它:
#+BEGIN_SRC python
>>> def fib2(n): # return Fibonacci series up to n
...     """Return a list containing the Fibonacci series up to n."""
...     result = []
...     a, b = 0, 1
...     while a < n:
...         result.append(a)    # see below
...         a, b = b, a+b
...     return result
...
>>> f100 = fib2(100)    # call it
>>> f100                # write the result
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]
#+END_SRC

这个例子演示了一些新的 Python 功能：
- return 语句从函数中返回一个值。
  不带表达式的 return 返回 None。过程结束后也会返回 None。
- 语句 result.append(b) 称为链表对象 result 的一个 方法 (method)。

方法是一个“属于”某个对象的函数，它被命名为 obj.methodename，这里的 obj 是某个
对象(可能是一个表达式)，methodename 是某个在该对象类型定义中的方法的命名。
** 4.7. 深入 Python 函数定义
在 Python 中，你也可以定义包含若干参数的函数。
这里有三种可用的形式，也可以混合使用。
*** 4.7.1. 默认参数值
最常用的一种形式是为一个或多个参数指定默认值。这会创建一个可以使用比定义时允许
的参数更少的参数调用的函数，例如:
#+BEGIN_SRC python
def ask_ok(prompt, retries=4, complaint='Yes or no, please!'):
    while True:
        ok = raw_input(prompt)
        if ok in ('y', 'ye', 'yes'):
            return True
        if ok in ('n', 'no', 'nop', 'nope'):
            return False
        retries = retries - 1
        if retries < 0:
            raise IOError('refusenik user')
        print complaint
#+END_SRC

这个函数可以通过几种不同的方式调用：

- 只给出必要的参数:
#+BEGIN_SRC python
ask_ok('Do you really want to quit?')
#+END_SRC

- 给出一个可选的参数:
#+BEGIN_SRC python
ask_ok('OK to overwrite the file?', 2)
#+END_SRC

- 或者给出所有的参数:
#+BEGIN_SRC python
ask_ok('OK to overwrite the file?', 2, 'Come on, only yes or no!')
#+END_SRC

这个例子还介绍了 in 关键字。它测定序列中是否包含某个确定的值。

*重要警告* : 默认值只被赋值一次。这使得当默认值是可变对象时会有所不同，比如列
表、字典或者大多数类的实例。例如，下面的函数在后续调用过程中会累积(前面)传给
它的参数:
#+BEGIN_SRC python
def f(a, L=[]):
    L.append(a)
    return L

print f(1)
print f(2)
print f(3)
#+END_SRC

这将会打印:
#+BEGIN_SRC python
[1]
[1, 2]
[1, 2, 3]
#+END_SRC

如果你不想在随后的调用中共享默认值，可以像这样写函数:
#+BEGIN_SRC python
def f(a, L=None):
    if L is None:
        L = []
    L.append(a)
    return L
#+END_SRC
*** 4.7.2. 关键字参数
函数可以通过 =关键字参数= 的形式来调用，形如 keyword = value。
例如，以下的函数:
#+BEGIN_SRC python
def parrot(voltage, state='a stiff', action='voom', type='Norwegian Blue'):
    print "-- This parrot wouldn't", action,
    print "if you put", voltage, "volts through it."
    print "-- Lovely plumage, the", type
    print "-- It's", state, "!"
#+END_SRC

接受一个必选参数( voltage )以及三个可选参数( state, action, 和 type )。
可以用以下的任一方法调用:
#+BEGIN_SRC python
parrot(1000)                                          # 1 positional argument
parrot(voltage=1000)                                  # 1 keyword argument
parrot(voltage=1000000, action='VOOOOOM')             # 2 keyword arguments
parrot(action='VOOOOOM', voltage=1000000)             # 2 keyword arguments
parrot('a million', 'bereft of life', 'jump')         # 3 positional arguments
parrot('a thousand', state='pushing up the daisies')  # 1 positional, 1 keyword
#+END_SRC

不过以下几种调用是无效的:
#+BEGIN_SRC python
parrot()                     # required argument missing
parrot(voltage=5.0, 'dead')  # non-keyword argument after a keyword argument
parrot(110, voltage=220)     # duplicate value for the same argument
parrot(actor='John Cleese')  # unknown keyword argument
#+END_SRC

在函数调用中，关键字的参数必须跟随在位置参数的后面。传递的所有关键字参数必须与
函数接受的某个参数相匹配，它们的顺序并不重要。任何参数都不可以多次赋值。

引入一个形如 **name 的参数时，它接收一个字典，该字典包含了所有未出现在形式参数
列表中的关键字参数。
这里可能还会组合使用一个形如 *name 的形式参数，它接收一个元组，包含了所有没有
出现在形式参数列表中的参数值。( *name 必须在 **name 之前出现)。
例如，我们这样定义一个函数:
#+BEGIN_SRC python
def cheeseshop(kind, *arguments, **keywords):
    print "-- Do you have any", kind, "?"
    print "-- I'm sorry, we're all out of", kind
    for arg in arguments:
        print arg
    print "-" * 40
    keys = sorted(keywords.keys())
    for kw in keys:
        print kw, ":", keywords[kw]
#+END_SRC
它可以像这样调用:
#+BEGIN_SRC python
cheeseshop("Limburger", "It's very runny, sir.",
           "It's really very, VERY runny, sir.",
           shopkeeper='Michael Palin',
           client="John Cleese",
           sketch="Cheese Shop Sketch")
#+END_SRC
当然它会按如下内容打印:
#+BEGIN_EXAMPLE
-- Do you have any Limburger ?
-- I'm sorry, we're all out of Limburger
It's very runny, sir.
It's really very, VERY runny, sir.
----------------------------------------
client : John Cleese
shopkeeper : Michael Palin
sketch : Cheese Shop Sketch
#+END_EXAMPLE
*** 4.7.3. 可变参数列表
最后，一个最不常用的选择是可以让函数调用可变个数的参数。
这些参数被包装进一个元组。在这些可变个数的参数之前，可以有零到多个普通的参数:
#+BEGIN_SRC python
def write_multiple_items(file, separator, *args):
    file.write(separator.join(args))
#+END_SRC
*** 4.7.4. 参数列表的分拆
另有一种相反的情况: 当你要传递的参数已经是一个列表，但要调用的函数却接受分开
一个个的参数值。这时候你要把已有的列表拆开来。
例如内建函数 range() 需要独立的 start，stop 参数。
你可以在调用函数时加一个 =*= 操作符来自动把参数列表拆开:
#+BEGIN_SRC python
>>> list(range(3, 6))            # normal call with separate arguments
[3, 4, 5]
>>> args = [3, 6]
>>> list(range(*args))            # call with arguments unpacked from a list
[3, 4, 5]
#+END_SRC

以同样的方式，可以使用 =**= 操作符分拆字典为关键字参数:
#+BEGIN_SRC python
>>> def parrot(voltage, state='a stiff', action='voom'):
...     print "-- This parrot wouldn't", action,
...     print "if you put", voltage, "volts through it.",
...     print "E's", state, "!"
...
>>> d = {"voltage": "four million", "state": "bleedin' demised", "action": "VOOM"}
>>> parrot(**d)
-- This parrot wouldn't VOOM if you put four million volts through it. E's bleedin' demised !
#+END_SRC
*** 4.7.5. Lambda 形式
通过 lambda 关键字，可以创建短小的匿名函数。
这里有一个函数返回它的两个参数的和：lambda a, b: a+b。
出于语法限制，它们只能有一个单独的表达式。
类似于嵌套函数定义，lambda 形式可以从外部作用域引用变量:
#+BEGIN_SRC python
>>> def make_incrementor(n):
...     return lambda x: x + n
...
>>> f = make_incrementor(42)
>>> f(0)
42
>>> f(1)
43
#+END_SRC

另一个用途是将一个小函数作为参数传递:
#+BEGIN_SRC python
>>> pairs = [(1, 'one'), (2, 'two'), (3, 'three'), (4, 'four')]
>>> pairs.sort(key=lambda pair: pair[1])
>>> pairs
[(4, 'four'), (1, 'one'), (3, 'three'), (2, 'two')]
#+END_SRC
*** 4.7.6. 文档字符串
文档字符串的概念和格式：
第一行应该是关于对象用途的简介。简短起见，以大写字母开头，以句号结尾。
如果文档字符串有多行，第二行应该空出来，与接下来的详细描述明确分隔。
第一行之后的第一个非空行决定了整个文档的缩进格式。
** 4.8. 插曲：编码风格
对于 Python， [[https://www.python.org/dev/peps/pep-0008][PEP 8]] 引入了大多数项目遵循的风格指导。它给出了一个高度可读，视觉
友好的编码风格。每个 Python 开发者都应该读一下，大多数要点都会对你有帮助：

- 使用 4 空格缩进，而非 TAB。
  在小缩进(可以嵌套更深)和大缩进(更易读)之间，4 空格是一个很好的折中。
  TAB 引发了一些混乱，最好弃用。
- 折行以确保其不会超过 79 个字符。
  这有助于小显示器用户阅读，也可以让大显示器能并排显示几个代码文件。
- 使用空行分隔函数和类，以及函数中的大块代码。
- 可能的话，注释独占一行
- 使用文档字符串
- 把空格放到操作符两边，以及逗号后面，但是括号里侧不加空格：a = f(1, 2) + g(3, 4)。
- 统一函数和类命名。
  推荐类名用 =驼峰命名= ，函数和方法名用 =小写_和_下划线= 。
  总是用 self 作为方法的第一个参数。
- 不要使用花哨的编码，如果你的代码的目的是要在国际化环境。Python 的默认情况下，
  UTF-8，甚至普通的 ASCII 总是工作的最好。
- 同样，也不要使用非 ASCII 字符的标识符，除非是不同语种的会阅读或者维护代码。
* 5. 数据结构
** 5.1. 关于列表更多的内容
*** 所的列表对象方法
#+BEGIN_SRC python
list.append(x)
#+END_SRC
    把一个元素添加到链表的结尾，相当于 a[len(a):] = [x]。

#+BEGIN_SRC python
list.extend(L)
#+END_SRC
    将一个给定列表中的所有元素都加到另一个列表中，相当于 a[len(a):] = L。

#+BEGIN_SRC python
list.insert(i, x)
#+END_SRC
    在指定位置插入一个元素。第一个参数是准备插入到其前面的那个元素的索引，
例如 a.insert(0, x) 会插入到整个链表之前，而 a.insert(len(a), x) 相当于
a.append(x)。

#+BEGIN_SRC python
lst.remove(x)
#+END_SRC
    删除链表中值为 x 的第一个元素。如果没有这样的元素，就会返回一个错误。

#+BEGIN_SRC python
list.pop([i])
#+END_SRC
    从链表的指定位置删除元素，并将其返回。如果没有指定索引，a.pop() 返回最后
一个元素。元素随即从链表中被删除。(方法中 i 两边的方括号示这个参数是可选的，
而不是要求你输入一对方括号，你会经常在 Python 库参考手册中遇到这样的标记。)

#+BEGIN_SRC python
list.index(x)
#+END_SRC
    返回链表中第一个值为 x 的元素的索引。如果没有匹配的元素就会返回一个错误。

#+BEGIN_SRC python
list.count(x)
#+END_SRC
    返回 x 在链表中出现的次数。

#+BEGIN_SRC python
list.sort(cmp=None, key=None, reverse=Fale)
#+END_SRC
    对链表中的元素就地进行排序
（参数可以用来自定义排序方法，参考 sorted() 的更详细的解释）。

#+BEGIN_SRC python
list.reverse()
#+END_SRC
    就地倒排链表中的元素。

也许大家会发现像 insert，rmove 或者 sort 这些修改列表的方法没有打印返回值
――――它们返回 None。在 python 中对所有可变的数据类型这是统一的设计原则。
*** 5.1.1. 把链表当作堆栈使用
链表方法使得链表可以很方便的做为一个堆栈来使用，堆栈作为特定的数据结构，最先进
入的元素最后一个被释放(后进先出)。用 append() 方法可以把一个元素添加到堆栈顶。
用不指定索引的 pop() 方法可以把一个元素从堆栈顶释放出来。
*** 5.1.2. 把链表当作队列使用
你也可以把链表当做队列使用，队列作为特定的数据结构，最先进入的元素最先释放
(先进先出)。不过，列表这样用效率不高。相对来说从列表末尾添加和弹出很快；在头部
插入和弹出很慢(因为为了一个元素，要移动整个列表中的所有元素)。

要实现队列，使用 [[https://docs.python.org/2.7/library/collections.html#collections.deque][collections.deque]] ，它为在首尾两端快速插入和删除而设计。
*** 5.1.3. 函式编程工具
对于链表来讲，有三个内置函数非常有用: filter()，map() 以及 reduce()。

**** filter(function, sequence)
返回一个 sequence(序列)，包括了给定序列中所有调用 function(item) 后返回值为
true 的元素(如果可能的话，会返回相同的类型)。

**** map(function, sequence)
为每一个元素依次调用 function(item) 并将返回值组成一个链表返回。

可以传入多个序列，函数也必须要有对应数量的参数，执行时会依次用各序列上对应的
元素来调用函数(如果某些序列比其它的短，就用 None 来代替)。如果把 None 做为一
个函数传入，则直接返回参数做为替代。

**** reduce(function, sequence)
返回一个单值，它是这样构造的：首先以序列的前两个元素调用函数 function，再以
返回值和第三个参数调用，依次执行下去。

如果序列中只有一个元素，就返回它，如果序列是空的，就抛出一个异常。

可以传入第三个参数作为初始值。如果序列是空的，就返回初始值，否则函数会先接收
初始值和序列的第一个元素，然后是返回值和下一个元素，依此类推。
*** 5.1.4. 列表推导式
列表推导式为从序列中创建列表提供了一个简单的方法。

列表推导式由包含一个表达式的括号组成，表达式后面跟随一个 for 子句，之后可以有零
或多个 for 或 if 子句。结果是一个列表，由表达式依据其后面的 for 和 if 子句上下
文计算而来的结果构成。
**** 5.1.4.1. 嵌套的列表推导式
列表推导式可以嵌套。
** 5.2. del 语句
有个方法可以从列表中按给定的索引而不是值来删除一个子项：del 语句。
语句 del 还可以从列表中删除切片或清空整个列表。

del 也可以删除整个变量。
此后再引用命名 a 会引发错误(直到另一个值赋给它为止)。
** 5.3. 元组和序列
元组和序列是序列类型(参见 [[https://docs.python.org/2.7/library/stdtypes.html#typesseq][Sequence Types
 — str, unicode, list, tuple, bytearray, buffer, xrange]] )中的两种。

这里介绍另一种标准序列类型：元组。

一个元组由数个逗号分隔的值组成。
元组在输出时总是有括号的，以便于正确表达嵌套结构。在输入时可以有或没有括号，
不过经常括号都是必须的(如果元组是一个更大的表达式的一部分)。

元组是不可变，不能给元组的一个独立的元素赋值。但是可以创建包含可变对象的元组。

虽然元组看起来类似于列表，它们经常用于不同的场景和不同的目的。
元组是 =不可变的= ，通常包含不同种类的元素并通过分拆或索引访问。
列表是 =可变的= ，它们的元素通常是相同的类型并通过迭代访问。

一对空的括号可以创建空元组；要创建一个单元素元组可以在值后面跟一个逗号。

语句 t = 12345, 54321, 'hello!' 是 =元组封装 (tuple packing)= 的一个例子：
值 12345，54321 和 'hello!' 被封装进元组。其逆操作是 =序列拆封= 。
序列拆封要求左侧的变量数目与序列的元素个数相同，等号右边可以是任何线性序列。

可变参数(multiple assignment)其实只是元组封装和序列拆封的一个结合。
** 5.4. 集合
Python 还包含了一个数据类型 =set (集合)= 。

集合是一个无序不重复元素的集。

基本功能包括关系测试和消除重复元素。
集合对象还支持 union(联合)，intersection(交)，difference(差) 和
sysmmetric difference(对称差集) 等数学运算。

大括号或 set() 函数可以用来创建集合。

类似 [[http://www.pythondoc.com/pythontutorial27/datastructures.html#tut-listcomps][列表推导式]] ，有一种 =集合推导式= 语法。
** 5.5. 字典
另一个非常有用的 Python 内建数据类型是 =字典= (参见 [[https://docs.python.org/2.7/library/stdtypes.html#typesmapping][Mapping Types — dict]] )。
字典在某些语言中可能称为 =联合内存 (associative memories)=
或 =联合数组 (associative arrays)= 。

序列是以连续的整数为索引，与此不同的是，字典以 /关键字/ 为索引，关键字可以是任意
不可变类型，通常用字符串或数值。
如果元组中只包含字符串和数字，它可以作为关键字，如果它直接或间接地包含了可变对
象，就不能当做关键字。

理解字典的最佳方式是把它看做无序的 =键:值= 对 (/key:value/ 对) 集合，键必须是互不相
同的 (在同一个字典之内) 。
一对大括号创建一个空的字典：{} 。
初始化链表时，在大括号内放置一组逗号分隔的 =键:值= 对，这也是字典输出的方式。

字典的主要操作是依据键来存储和析取值。也可以用 del 来删除 =键:值= 对 (/key:value/)。

对一个字典执行 /keys()/ 将返回一个字典中所有关键字组成的无序列表。
使用 /in/ 关键字可以检查字典中是否存在某个关键字。

dict() 构造函数可以直接从 key-value 对中创建字典。

字典推导式可以从任意的键值表达式中创建字典。
** 5.6. 循环技巧
