#+TITLE: 传统企业与互联网的所有竞争最终都是效率之争

@See https://mp.weixin.qq.com/s/b5zTF5NTF7AJnZ_oqqfkqw

以下文章来源于刘润 ，作者刘润

经常有同学问我，怎么看互联网对传统企业的挑战。
这个问题很大。
大到我在线下，有时要花 3 个小时才可以分享，它涉及到互联网这 20 多年的发展，本质上互联网到底给商业带来了什么。

* 一、连接

2013 年，这一年非常特殊，很多泰斗级的企业家，不管是张瑞敏还是俞敏洪，还是刘永好，都纷纷说传统企业受到了互联网
的挑战。那时，还催生了一个非常火的词“降维打击”。

什么是降维打击？
这个词源自刘慈欣科幻小说《三体》，是指当高维文明打击你的时候，你的什么氢弹、原子弹一点用没有，直接就没了。
就好像要攻击一个人，高维文明的人向你扔一个小纸片，你直接就从三维立体的人一下子变成相片，被挂在了墙上。

这是很恐怖的打法。
那为什么这些互联网公司开始挑战传统企业？互联网经济相对以前的传统经济又有什么区别？


我们就从线下经济开始讲起，说说这些年互联网给商业带来的变化。

商业的本质是交易，商家能接触到更多的买家，卖出的商品也就会越多。

没有互联网之前，线下商业什么最重要？地段。

为什么？
=因为好地段会带来更多的人流，而在没有互联网之前，地段和人流是不可分割的，人流是无法脱离地段而单独存在的。=
所以才有李嘉诚说的房地产金科玉律“地段、地段、还是地段”。

而到了互联网时代，可以网上购物了，这时人流和地段就可以分开了。
同样是把商品触达给更多的买家，以前靠地段，现在完全可以借助互联网实现。
=人们在百度上搜索内容、在阿里搜索商品、在腾讯上和朋友社交，这些本质上都是流量。=
这时，我们到了流量经济时代。


再往后，就到了 2013 年。

很多人说这是移动互联网时代，那移动互联网时代和以前有什么不同？移动互联网时代以前，我们上网都是用 PC 的，即使
用笔记本电脑，我们也要带着它找到一个能坐下来，有网络的地方才可以用。但是手机能上网就不一样了。这意味着，我可以随时随地的和网络保持连接。再往深想一层，这也意味着，拿着这个手机的人可以随时随地和网络连接。
=这是移动互联网和PC互联网最大的不同，人随时随地可以连接网络了。=

那这时，商家再想让商品获得更多买家的关注，抢夺的还是流量吗？不是了，这时商家们抢夺的是人们的时间。这是正在发生
的事，你可以问问自己，你每天花在各种 APP 的时间是多少？据统计，我们现在每个人平均每天在微信上要花 60 分钟的
时间。
=移动互联网时代的竞争，就是抢夺与用户交互“时间”的竞争。=


那下一个时代呢？我认为下一个时代可能是可穿戴设备的时代，那时我们身上的可穿戴设备，比如手环、手表、眼镜、甚至
鞋子、衣服等等都可以联网，流量会越来越碎片化。但可穿戴设备的时代，我不认为是这波变化的终点。未来，我们一定会
进入万物互联时代，就是几乎所有你用到的、看到的设备都将可以和互联网连接。这是一个大变革时代，互联网的发展还没
有走完。


那么这波互联网浪潮，他背后最本质的推动力是什么呢？连接。没有互联网，我们靠地段连接大家；有了 PC 互联网，我们
靠流量连接；到了移动互联网，我们争夺和用户时间上的连接。

所以马化腾才会说：我们把搜索业务与搜狐合作，电商业务与京东合作，我们回归到最本质的就是做连接器。

=因为连接，就会让距离缩短，距离缩短，就会让信息传递越来越快。=
因为信息传递越来越快，这也就诞生了很多新的商业模式。


* 二、信息对称

诞生了什么新的商业模式？

=信息传递越来越快，就会消除更多的信息不对称。=

什么意思？
举个简单的例子，我们在线下买件衣服，经常要和店员讨价还价的，为什么？
因为店员心理一定有个底价的，但是你不知道多少。他会想办法试探你最高能付的价格是多少。
所以你们就要讨价还价。
但是今天呢。你看上一件衣服，是不是你会在淘宝等电商平台搜一搜。
如果电商平台上的同样的商品更便宜，你是不是就在网上买了。
这本质是解就消除了信息不对称。


再比如大众点评和麦当劳。

我以前去美国出差，吃饭的时候我一般会去麦当劳。
为什么？
因为人生地不熟，我不知道其他店的食物是否符合我的口味，麦当劳因为是连锁，味道还差不太多吧。
所以我去麦当劳。

现在呢，现在你可能会跟我说，你怎么不看看大众点评啊。
对，现在我们都习惯了，如果去一个陌生地方点餐，打开点评看看。
为什么？
因为在没有点评这样的软件之前，我是不知道其他餐厅信息的，不知道他的口感怎么样。
但点评软件消除了这种信息不对称。

所以，=我认为基于信息不对称的商业模式，或早或晚都会被消灭的。=


那再往深层想一下呢，你会发现，你打开点评后，你已经不去记住那些店名了，你只会记住这家店是不是 5 颗星，评价怎么
样？那这样，我们熟知的那些加盟、连锁的商业模式也就会面临一些挑战。
所以，距离一旦缩短，信息一旦对称之后，很多我们以前所熟知的东西，都会完全不一样了。
换句话说， =我们所坚信的一切东西，都是针对某个特殊环境的临时解决方案。=


* 三、互联网加减法

那在这个万变的时代，什么东西是不变的？

=让消费者获益，为用户创造价值，这件事永远是不会变的。=

在商业中，企业如何为用户创造价值？

我把他分解为创造价值环节和传递价值环节。
什么是创造价值？什么是传递价值？

海尔生产了一款冰箱，苏宁把他卖掉了。那谁创造了价值？海尔。苏宁做了传递价值。

举个难一点的例子。
我们看湖南卫视的综艺节目。那湖南卫视是创造价值还是传递价值？
有人说那肯定是创造价值。
确实，综艺节目是创造出来给观众看的。但是它是不是通过湖南卫视这个媒介传递给我们观众的，所以它也有传递价值部分。
那互联网一来，对哪个部分冲击最大？一定是传递价值部分，我们可以看网综，我们不一定用湖南卫视这一个传递媒介了，
我们可以在芒果 TV、可以在爱奇艺、可以在优酷上看一些综艺了。

所以， =互联网的到来，首先是对传递价值部分切了一刀。=


再比如餐厅的大堂，我们说这是传递价值，因为他把在厨房做出来的菜，让食客在大堂吃了。所以外卖软件在这个传递价值
部分切了一刀。是不是现在就有很多店没有堂吃了。我们叫他外卖店。

那创造价值部分的厨房呢？互联网的到来，一些 O2O 大厨上门软件同样切了一刀。

为什么？厨房真正创造价值的是谁？是厨具？食材吗？不是，是大厨。如果有一款软件，能把大厨叫上门帮你做一桌菜。是不
是在创造价值环节又切了一刀。

=互联网带来的连接，大幅提高了沟通效率，降低了交易成本，在商业上的传递价值、创造价值环节一刀一刀切下去。=
所以才会导致传统企业会遇到互联网企业的挑战，甚至有人说这是“降维打击”。


* 四、互联网减

这种“降维打击”，我们说首先打击的是传递价值部分。

在没有互联网之前，在传递价值这个环节，商家是受益于信息不对称的，这才有了讨价还价等形式。
互联网的连接，越来越消减了这种不对称，这就是互联网减。

那具体是如何消减这种信息不对称呢？

=在传递价值环节，我们可以把它解构为三个部分，叫做信息流、资金流和物流。=

最简单的我们去商场买件衣服。
我打量一件衣服，左看，右看，看看材质、价格，比比大小，觉得不错，还可以试一下。
这些其实是什么？这些其实是信息流。就是我了解这件商品的信息。
然后我决定下单购买，老板开单，我刷卡。这是资金流。
刷卡之后，柜台员工装好袋，递到我手上，我就拎走了。这是物流。
因为在线下这个过程特别快，你可能不会这样看一次购物过程。


但是互联网干了什么？
它把信息流、资金流、物流给分开了。

淘宝做什么的？有人说淘宝什么都做。
是，他可能什么都卖。但其实淘宝做的是信息流，就是它展示的是商品信息。
那支付宝做的是什么？支付宝做的是资金流。
菜鸟网络呢？菜鸟网络做的是物流。

=当互联网公司把这三个要素分开之后，它利用连接的优势，就可以大幅提高信息处理的效率。=


就以物流为例，我们理解的物流是不是这样，我们在淘宝或者京东上下单，接到订单后，卖家开始发货，最终送到你手上。

但事实上，这太慢了。尤其是遇到双 11 这样的节日。
那现在的物流是什么样的？
他们会建骨干节点仓库，用大数据预估某个地方大概需要什么货，提前就把货储备在你的周边。
等你一下单，会从你最近的仓库给你发过来。

互联网公司这是在做什么？一个词，效率。
=互联网公司想尽一切办法去提高信息的效率、资金的效率、物流的效率。所以最后所有的竞争都是效率之争。=


我们在往后推演，在未来，物流会不会有可能变成这样。

互联网公司基于大数据等等判断，判断你肯定要买某款产品，于是就已经安排快递上门了。
如果，快递够快，他可能会提前就站在你家门口。那时，快递心里想的是，怎么还不下单呢？
结果你一下单，他就咚咚咚敲门。
这叫预测式购物。
这是不是更会提高我们购物的效率。

所以，=最后所有的竞争都是效率之争，互联网的一切优势，都是效率优势。=


* 五、互联网加

互联网减在商业上的传递价值环节砍了一刀，提高了效率。

那互联网加呢？
互联网加是一旦商业中的传递价值环节被缩减后，那么用户跟企业之间的距离就缩短了。
也就意味着，我们终于有机会让用户的需求能反馈到企业这边来了，这时，作为企业就能更好的满足用户的需求。
这就是互联网加。

具体到用户价值，我们也可以分三个层次，分别是功能、体验、个性。


沙发是用来坐的，矿泉水是用来喝的，这是功能价值。

什么是体验价值？
我们现在经常听很多互联网公司产品经理说，要给用户极致的体验。
他们为什么这样？
因为不这样，他们就把你的 APP 卸载了。
我们现在获取一个新的用户很难，成本很高。但是用户一旦用的不爽，卸载是不是非常容易。
所以，黎万强说过一句话，他说：

用户真正掌握主权，不再是我们，这是一个最大的变化。

用户掌握了主权这件事，就逼的互联网这些产品经理，不得不想尽各种办法给用户极致的体验。
在 PC 互联网时代，不知道你有没有用过 ERP、OA 等系统，那时候软件用起来怎么样？
是不是特别难用，还要学习，还要看操作手册。
现在的 APP 软件呢？是不是比以前简单、容易上手多了，体验越来越好了。

这是移动互联网给我们用户带来的主权。


最后，我们说说个性化，C2B。

就以洗衣机生产线为例。
作为用户，我们现在就可以在家里定制我们自己的洗衣机，一共可能有 25 个模块可以定制。
比如带不带烘干功能？要机械面板还是电子面板？颜色是红的还是白的？等等。
你定制好后，数据就传到了工厂，然后工厂就开始生产。
那么这条生产线，生产出来的每一台洗衣机就都是不一样的。
这就满足了用户的个性化需求。

这样的反向定制方式，它解决了 2 个对制造业来说非常重要的问题。
 - 第 1 个问题，解决了现金流问题，因为用户是先付款，工厂再生产。
 - 第 2 个问题，解决库存压力。以前我们是每一个冰箱品类要生产很多，等着用户来选，这样做肯定有库存，最终会有
   浪费。

但先定制，再生产，就解决了库存问题。

在解决上面两个问题的基础上，还同时满足了用户的个性化需求。

这就是互联网加，在创造价值环节，由于互联网的连接导致距离缩短，用户的需求可以反馈到企业，企业就可以在功能、体
验、个性化方面更好地满足用户的需求，提高了效率。

所以说，最后所有的竞争都是效率之争，互联网的一切优势，都是效率优势。

如果你是一位身处传统企业，想向互联网公司学习、转型的朋友。
那么我希望你能理解，你曾经最引以为豪的那些东西，不一定再有价值，不能要死死的抱住不放。那些只是你的感情的寄托，
时代在变就必须要找到新的路径。
我祝愿你能够拥抱互联网，拥抱变革的时代。
而对其他朋友，我想说，互联网的一切优势，都是效率优势，无论你从事什么行业，最后所有的竞争都是效率之争。

我祝福你能紧紧把握互联网的效率优势，成就辉煌。
