* Cassandra 安装与操作
** 1、获取 Cassandra 介质
下载并解压缩 apache-cassandra-1.1.2-bin.tar.gz

** 2、运行配置 Cassandra
执行以下指令启动。
$ ./cassandra -f

f 的意思是前台运行，可以随时 Ctrl+C 终止。

需要修改 cassandra.yaml 中的以下配置的路径:

data_file_directories:
    - /Nautilus/cassandra/data 
commitlog_directory: /Nautilus/cassandra/commitlog
saved_caches_directory: /Nautilus/cassandra/saved_caches

修改 log4j-server.properties 中指定的 log 路径

log4j.appender.R.File=/Nautilus/cassandra/system.log

** 3、使用 cassandra-cli 测试
格式：bin/cassandra-cli -h host -p rpc_port
这里我们执行以下指令

./cassandra-cli -h 127.0.0.1 -p 9160
 
Connected to: "Test Cluster" on 127.0.0.1/9160
Welcome to Cassandra CLI version 1.1.2
 
Type 'help;' or '?' for help.
Type 'quit;' or 'exit;' to quit.
 
[default@unknown]

成功登录 cli

** 4、创建测试 keyspace
创建一个叫 NOAH 的 keyspace

[default@unknown] create keyspace NOAH;

使用 NOAH 的 keyspace

[default@unknown] use NOAH;

** 5、创建测试 column family
创建一个叫 Users 的 column family

[default@NOAH] create column family Users;

** 6、存入一些测试数据到 Users
[default@NOAH] set Users[utf8('1234')][utf8('name')] = utf8('张三');
[default@NOAH] set Users[utf8('1234')][utf8('password')] = utf8('abcd');

** 7、查询插入的测试数据
[default@NOAH] get Users[utf8('1234')];

我们可以观察到列名并没有显示为实际的字符串，需要使用 assume 指令

[default@NOAH] assume Users keys as utf8;
Assumption for column family 'Users' added successfully.
[default@NOAH] assume Users comparator as utf8;
Assumption for column family 'Users' added successfully.
[default@NOAH] assume Users validator as utf8;
Assumption for column family 'Users' added successfully.
 
[default@NOAH] get Users[utf8('1234')];

** 8、java 操作 cassandra（thrift）

** 9、java 操作 cassandra（hector）
hector 提供了更易用的操作 api
