#+TITLE:Generating an SSH key

SSH keys are a way to identify trusted computers without involving passwords.
You can generate an SSH key and add the public key to your GitHub account by
following the procedures outlined in this section.

We recommend that you regularly [[https://help.github.com/articles/keeping-your-ssh-keys-and-application-access-tokens-safe][review your SSH keys list]] and revoke any that
haven't been used in a while.

* [[https://help.github.com/articles/checking-for-existing-ssh-keys][Checking for existing SSH keys]]

Before you generate an SSH key, you can check to see if you have any existing
SSH keys.

* [[https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent][Generating a new SSH key and adding it to the ssh-agent]]

After you've checked for existing SSH keys, you can generate a new SSH key
to use for authentication, then add it to the ssh-agent.

* [[https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account][Adding a new SSH key to your GitHub account]]

To configure your GitHub account to use your new (or existing) SSH key,
you'll also need to add it to your GitHub account.

* [[https://help.github.com/articles/testing-your-ssh-connection][Testing your SSH connection]]

After you've set up your SSH key and added it to your GitHub account, you can
test your connection.
